services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: "api"
    restart: unless-stopped
    ports:
      - 3333:3333
    env_file:
      - ./apps/api/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: orquestrando
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
